### ISSUE TITLE
A query about the usage of umitools

### ISSUE THREAD

**Issue by WT215** [jdblischak/singleCellSeq#57]
Hello!

I am trying to realize the Read mapping step described in your excellent paper "Batch effects and the effective design of single-cell gene expression studies" and I am looking into the file `code/trim.sh`.

For the sentence in that paper: 

> To handle the UMI sequences at the 5′ end of each read, we used umitools39 to find all reads with a UMI of the pattern NNNNNGGG (reads without UMIs were discarded). 

May I ask how to discard reads without UMIs (is it accomplished using a certain option in umitools)? I observed that some reads have the first 8 bps "NNNNNGGG", where the last 3 are not all "G". Are those reads the reads without UMI that you mentioned in the paper?

By the way, the umitools seems to be updated, and the original `code/trim.sh` may not work. Would you mind teaching me how to achieve that step in the paper using the latest version's umitools please?

Thanks a lot!
Wenhao

**Comment by jdblischak** [comment]
Hi @WT215!

> I am trying to realize the Read mapping step described in your excellent paper "Batch effects and the effective design of single-cell gene expression studies" and I am looking into the file code/trim.sh.

Thanks for the kind words. I'm glad you enjoyed the paper!

> May I ask how to discard reads without UMIs (is it accomplished using a certain option in umitools)?

I'm not sure I understand your question. `trim.sh` runs the following code ([line 25](https://github.com/jdblischak/singleCellSeq/blob/339176da78424647e6efcebcd84bb1207726be48/code/trim.sh#L25)):

```
umitools trim --end 5 --verbose --top 50 $FILE NNNNNGGG \
  --invalid $INVALID_DIR/$BASE.invalid.fastq \
2> $INVALID_DIR/$BASE.trim.stats.txt | gzip -c > $OUTDIR/$BASE.trim.fastq.gz
```

If the first 8 base pairs of the read do not match the pattern NNNNNGGG (where N can be any base), then it discarded in the FASTQ file specified by the flag `--invalid`.

> I observed that some reads have the first 8 bps "NNNNNGGG", where the last 3 are not all "G".
Are those reads the reads without UMI that you mentioned in the paper?

I don't follow. In which file are you observing these reads? Is this before or after running `umitools trim`? If the first 8 bps are NNNNNGGG, then how can the last 3 not be a G?

> By the way, the umitools seems to be updated, and the original code/trim.sh may not work. Would you mind teaching me how to achieve that step in the paper using the latest version's umitools please?

What makes you suspect that umitools was updated? The only commit that has been made since January 2017 was a commit in June 2017 that updated the title of the README (https://github.com/brwnj/umitools/commit/0b823e1fe6900de45cd410aef6e2831a7e0650c9). Did you try to run it and get an error? If yes, please provide more details on the input file, command you ran, the error message you received, and your computational setup (e.g. operating system and version of Python).

However, I wouldn't invest too much time in learning [umitools](https://github.com/brwnj/umitools). It was a useful package, but it has some flaws (https://github.com/brwnj/umitools/issues/11), and is not being actively developed. For our current projects, we use [UMI-tools](https://github.com/CGATOxford/UMI-tools). See [here](https://github.com/jdblischak/singlecell-qtl/blob/2d9aea02a33ed5c195092f390b03568daa2ed8a5/Snakefile#L277) for an example of how we currently use `umi_tools extract` to remove the UMIs.

I hope this helped answer some of your questions. If you provide more information, I'd be happy to further advise.

**Comment by WT215** [comment]
Hi @jdblischak , thank you for your reply! I just realized that `umitools` and `umi_tools` are two different tools. I have run `umi_tools` successfully, and I am going to do the alignment.

Best wishes,
Wenhao

**Comment by jdblischak** [comment]
@WT215 It is confusing how similar their names are. I'm glad you have UMI-tools working now. Best of luck with the rest of the analysis!
